### ISSUE TITLE
should support to keep some number of recently published of artifacts

### ISSUE THREAD

**Issue by hoatle** [c-hive/gha-remove-artifacts#26]
thank for your helpful action, can you add support for keeping a configurable number of recently published artifacts?

For example:

```
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        keep-recent: 7 # keep the number of recently published artifacts 
        skip-tags: true
```

so that even if those 7 recently published artifacts are older than 1 month, the action will not delete them.
