### ISSUE TITLE
Feature request: skip-recent-commit option

### ISSUE THREAD

**Issue by SadPencil** [c-hive/gha-remove-artifacts#28]
```
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        skip-recent: 5
```
the `skip-recent` options specific the number of artifacts, rather than commits. So, suspose my action generates more than one artifacts per commit (even more, not a constant number. It depends. ), while I want to keep recently 3 commits' artifacts, a new option which might be called `skip-recent-commit` might be handy.
