### ISSUE TITLE
`GITHUB_ACTION` environment variable is not set error

### ISSUE THREAD

**Issue by dominikfoldi** [c-hive/gha-remove-artifacts#30]
Until now the action was working perfectly, but today we got the following error when it tried to run in our scheduled workflow:

`##[error]Error: [@octokit/auth-action] 'GITHUB_ACTION' environment variable is not set. @octokit/auth-action is meant to be used in GitHub Actions only.`

Our configuration:
```
uses: c-hive/gha-remove-artifacts@v1
with:
  age: '14 days'
  skip-tags: true
```
