### ISSUE TITLE
Task fails with "Abuse detected"

### ISSUE THREAD

**Issue by JesperNJessen** [c-hive/gha-remove-artifacts#35]
My task started failing on October 21. Is there some limit I need to be aware of?

Log:
(This continues until the time limit is reached)
```
Run c-hive/gha-remove-artifacts@v1
Maximum artifact age: 1 month ( created before 2020-09-29T01:34:46+00:00 )
Abuse detected for request GET https://api.github.com/repos/<org>/<repo>/actions/runs/247833771/artifacts?per_page=100, retry count: 0
Retrying after 60 seconds!
Abuse detected for request GET https://api.github.com/repos/<org>/<repo>/actions/runs/247824105/artifacts?per_page=100, retry count: 1
Retrying after 60 seconds!
Abuse detected for request GET https://api.github.com/repos/<org>/<repo>/actions/runs/247824104/artifacts?per_page=100, retry count: 2
Retrying after 60 seconds!
```

YML file:

```
name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
```
