### ISSUE TITLE
Storage not freed after purging all artifacts?

### ISSUE THREAD

**Issue by 96312** [c-hive/gha-remove-artifacts#38]
Hey folks, I'm fairly new to workflows and wanna understand why running this workflow couldn't purge all the artifacts from my github quota?

Screenshot of the workflow which gets initated on [push] to master

![image](https://user-images.githubusercontent.com/34262180/103474437-cb545900-4dc9-11eb-97e8-8e59942b718c.png)

Here's my workflow file : 

```
name: Remove old artifacts

on:
  push:
    branches: [master]

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 day"
```

and here's a screenshot of my github storage space:

![image](https://user-images.githubusercontent.com/34262180/103474457-fb036100-4dc9-11eb-9f8d-3ede920eb2ba.png)

Can y'all please help me figure out what exactly am I doing wrong?
