### ISSUE TITLE
HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by codyhod** [c-hive/gha-remove-artifacts#49]
Action is failing consistently for the past few weeks, regardless of when it's ran or what other tasks are ongoing.

```
Skipping recent artifact (id: 216039564, name: uberjar).
Error: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
(node:1556) UnhandledPromiseRejectionWarning: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/_actions/c-hive/gha-remove-artifacts/v1/dist/index.js:11413:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Job.doExecute (/home/runner/work/_actions/c-hive/gha-remove-artifacts/v1/dist/index.js:14169:18)
```

The specific workflow we're using:

```YAML
name: Remove old artifacts
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
          skip-tags: true
          skip-recent: 5
```

Perhaps there has been a change to [secondary rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits)?
