### ISSUE TITLE
Add Support for private Repositories 

### ISSUE THREAD

**Issue by Myzumi** [c-hive/gha-remove-artifacts#50]
Hi there,

Im trying to use this action in a private repository to keep only the 5 latest artifacts, sadly this does not work on private repositories asn seen below

![image](https://user-images.githubusercontent.com/34660019/166721493-86e34773-f017-4f5f-8a41-c329159e67ba.png)

Would love to see support for private repos

**Comment by StephenHodgson** [comment]
I'm using this on a private repo atm, so this error might be due to something else entirely/

**Comment by shohei1029** [comment]
You may need to give the write permission to the workflow.
![image](https://user-images.githubusercontent.com/7954174/229958430-12d08a08-0104-444b-90cc-538de1ade629.png)

**Comment by alpipego** [comment]
This can also be done in the job definition via `permission: write-all`:

```
...
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          skip-tags: true
          skip-recent: 2
```

**Comment by jramos** [comment]
`permission: write-all` is too broad. You only need write permissions for "Actions" to delete artifacts. [Ref](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps#repository-permissions-for-actions)

```yaml
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 month'
```
