### ISSUE TITLE
Request quota exhausted for request GET

### ISSUE THREAD

**Issue by dschinkel** [c-hive/gha-remove-artifacts#51]
How the hell do I get past this? Frustrating

**Errors**
```
Request quota exhausted for request GET https://api.github.com/repos/dschinkel/we-do-tdd/actions/runs?per_page=100, number of total global retries: 1
Retrying after 0 seconds!
Error: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
(node:1535) UnhandledPromiseRejectionWarning: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/_actions/c-hive/gha-remove-artifacts/v1/dist/index.js:[11](https://github.com/dschinkel/we-do-tdd/runs/6875740490?check_suite_focus=true#step:2:11)413:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Job.doExecute (/home/runner/work/_actions/c-hive/gha-remove-artifacts/v1/dist/index.js:14169:18)
(node:1535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1535) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1535) UnhandledPromiseRejectionWarning: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/_actions/c-hive/gha-remove-artifacts/v1/dist/index.js:114[13](https://github.com/dschinkel/we-do-tdd/runs/6875740490?check_suite_focus=true#step:2:13):23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    
Request quota exhausted for request DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}, number of total global retries: 70
Retrying after 3424 seconds!
```

`gha-remove-artifacts` is retrying way too many times and then causing this problem.  How can we limit retries with this plugin?

**Workflow**

```
name: Remove-Old-Github-Action-Artifacts
on:
  push:
    branches:
      - master
  schedule:
    # Every day at 4am
    - cron: '0 4 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Remove artifacts older than 30 seconds
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '60 seconds'
```
